
import { Geist, Geist_Mono, Anta } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { SessionProvider } from "next-auth/react";
import DynamicGrid from "@/components/DynamicGrid";





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anta = Anta({
  variable: "--font-anta",
  subsets: ["latin"],
  weight: "400"
});

// To set dark mode


export const metadata = {
  title: "Prajwal Rangegowda",
  description: "Generated by create next app",
  icons: { icon: "/favicon.ico?v=2" , appleIcon: "/favicon.ico?v=2" },
  manifest: "/manifest.json",
  

};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} `}>
        <DynamicGrid/>
      <Header />
        {children }
        <Footer />
      </body>
    </html>
  );
}
